services:
  nginx:
    image: nginx
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress
    build: requirements/wordpress/.
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - database_password
      - wp_password
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
  mariadb:
    image: mariadb
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always
networks:
  inception:

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/bde-souz/data
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/bde-souz/data
      o: bind
secrets:
  database_password:
    file: ../secrets/database_password.txt
  wp_password:
    file: ../secrets/wp_password.txt