services:
  nginx:
    image: nginx
    build: requirements/nginx/.
    container_name: nginx
    # env_file: 
    #   - .env
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress
    build: requirements/wordpress/.
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
  mariadb:
    image: mariadb
    build: requirements/mariadb/.
    container_name: mariadb
    # env_file:
    #   - ./.env
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always
    # expose:
    #   - "3306"
networks:
  inception:

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: ../data
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: ../data
      o: bind